services:
  mongoose-rest:
    build:
      context: .
      target: development
    command: pnpm run start:dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app